name: small_projects
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  shared_preferences: ^2.0.20
  http: ^0.13.5
  hive: ^2.2.3 # Hive
  hive_flutter: ^1.1.0 #Hive

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3 # Hive
  build_runner: ^2.1.11 # Hive

flutter:
  uses-material-design: true
